// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RenderAction.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AbyssCLI.ABI {

  /// <summary>Holder for reflection information generated from RenderAction.proto</summary>
  public static partial class RenderActionReflection {

    #region Descriptor
    /// <summary>File descriptor for RenderAction.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RenderActionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJSZW5kZXJBY3Rpb24ucHJvdG8izwIKDFJlbmRlckFjdGlvbhI1Cg5jcmVh",
            "dGVfZWxlbWVudBgBIAEoCzIbLlJlbmRlckFjdGlvbi5DcmVhdGVFbGVtZW50",
            "SAASMQoMbW92ZV9lbGVtZW50GAIgASgLMhkuUmVuZGVyQWN0aW9uLk1vdmVF",
            "bGVtZW50SAASNQoOcmVtb3ZlX2VsZW1lbnQYAyABKAsyGy5SZW5kZXJBY3Rp",
            "b24uUmVtb3ZlRWxlbWVudEgAGjYKDUNyZWF0ZUVsZW1lbnQSEQoJcGFyZW50",
            "X2lkGAEgASgFEhIKCmVsZW1lbnRfaWQYAiABKAUaOAoLTW92ZUVsZW1lbnQS",
            "EgoKZWxlbWVudF9pZBgBIAEoBRIVCg1uZXdfcGFyZW50X2lkGAIgASgFGiMK",
            "DVJlbW92ZUVsZW1lbnQSEgoKZWxlbWVudF9pZBgBIAEoBUIHCgVpbm5lckIP",
            "qgIMQWJ5c3NDTEkuQUJJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AbyssCLI.ABI.RenderAction), global::AbyssCLI.ABI.RenderAction.Parser, new[]{ "CreateElement", "MoveElement", "RemoveElement" }, new[]{ "Inner" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::AbyssCLI.ABI.RenderAction.Types.CreateElement), global::AbyssCLI.ABI.RenderAction.Types.CreateElement.Parser, new[]{ "ParentId", "ElementId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AbyssCLI.ABI.RenderAction.Types.MoveElement), global::AbyssCLI.ABI.RenderAction.Types.MoveElement.Parser, new[]{ "ElementId", "NewParentId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AbyssCLI.ABI.RenderAction.Types.RemoveElement), global::AbyssCLI.ABI.RenderAction.Types.RemoveElement.Parser, new[]{ "ElementId" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RenderAction : pb::IMessage<RenderAction>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RenderAction> _parser = new pb::MessageParser<RenderAction>(() => new RenderAction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RenderAction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AbyssCLI.ABI.RenderActionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RenderAction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RenderAction(RenderAction other) : this() {
      switch (other.InnerCase) {
        case InnerOneofCase.CreateElement:
          CreateElement = other.CreateElement.Clone();
          break;
        case InnerOneofCase.MoveElement:
          MoveElement = other.MoveElement.Clone();
          break;
        case InnerOneofCase.RemoveElement:
          RemoveElement = other.RemoveElement.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RenderAction Clone() {
      return new RenderAction(this);
    }

    /// <summary>Field number for the "create_element" field.</summary>
    public const int CreateElementFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AbyssCLI.ABI.RenderAction.Types.CreateElement CreateElement {
      get { return innerCase_ == InnerOneofCase.CreateElement ? (global::AbyssCLI.ABI.RenderAction.Types.CreateElement) inner_ : null; }
      set {
        inner_ = value;
        innerCase_ = value == null ? InnerOneofCase.None : InnerOneofCase.CreateElement;
      }
    }

    /// <summary>Field number for the "move_element" field.</summary>
    public const int MoveElementFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AbyssCLI.ABI.RenderAction.Types.MoveElement MoveElement {
      get { return innerCase_ == InnerOneofCase.MoveElement ? (global::AbyssCLI.ABI.RenderAction.Types.MoveElement) inner_ : null; }
      set {
        inner_ = value;
        innerCase_ = value == null ? InnerOneofCase.None : InnerOneofCase.MoveElement;
      }
    }

    /// <summary>Field number for the "remove_element" field.</summary>
    public const int RemoveElementFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AbyssCLI.ABI.RenderAction.Types.RemoveElement RemoveElement {
      get { return innerCase_ == InnerOneofCase.RemoveElement ? (global::AbyssCLI.ABI.RenderAction.Types.RemoveElement) inner_ : null; }
      set {
        inner_ = value;
        innerCase_ = value == null ? InnerOneofCase.None : InnerOneofCase.RemoveElement;
      }
    }

    private object inner_;
    /// <summary>Enum of possible cases for the "inner" oneof.</summary>
    public enum InnerOneofCase {
      None = 0,
      CreateElement = 1,
      MoveElement = 2,
      RemoveElement = 3,
    }
    private InnerOneofCase innerCase_ = InnerOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InnerOneofCase InnerCase {
      get { return innerCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearInner() {
      innerCase_ = InnerOneofCase.None;
      inner_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RenderAction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RenderAction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CreateElement, other.CreateElement)) return false;
      if (!object.Equals(MoveElement, other.MoveElement)) return false;
      if (!object.Equals(RemoveElement, other.RemoveElement)) return false;
      if (InnerCase != other.InnerCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (innerCase_ == InnerOneofCase.CreateElement) hash ^= CreateElement.GetHashCode();
      if (innerCase_ == InnerOneofCase.MoveElement) hash ^= MoveElement.GetHashCode();
      if (innerCase_ == InnerOneofCase.RemoveElement) hash ^= RemoveElement.GetHashCode();
      hash ^= (int) innerCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (innerCase_ == InnerOneofCase.CreateElement) {
        output.WriteRawTag(10);
        output.WriteMessage(CreateElement);
      }
      if (innerCase_ == InnerOneofCase.MoveElement) {
        output.WriteRawTag(18);
        output.WriteMessage(MoveElement);
      }
      if (innerCase_ == InnerOneofCase.RemoveElement) {
        output.WriteRawTag(26);
        output.WriteMessage(RemoveElement);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (innerCase_ == InnerOneofCase.CreateElement) {
        output.WriteRawTag(10);
        output.WriteMessage(CreateElement);
      }
      if (innerCase_ == InnerOneofCase.MoveElement) {
        output.WriteRawTag(18);
        output.WriteMessage(MoveElement);
      }
      if (innerCase_ == InnerOneofCase.RemoveElement) {
        output.WriteRawTag(26);
        output.WriteMessage(RemoveElement);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (innerCase_ == InnerOneofCase.CreateElement) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreateElement);
      }
      if (innerCase_ == InnerOneofCase.MoveElement) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MoveElement);
      }
      if (innerCase_ == InnerOneofCase.RemoveElement) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RemoveElement);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RenderAction other) {
      if (other == null) {
        return;
      }
      switch (other.InnerCase) {
        case InnerOneofCase.CreateElement:
          if (CreateElement == null) {
            CreateElement = new global::AbyssCLI.ABI.RenderAction.Types.CreateElement();
          }
          CreateElement.MergeFrom(other.CreateElement);
          break;
        case InnerOneofCase.MoveElement:
          if (MoveElement == null) {
            MoveElement = new global::AbyssCLI.ABI.RenderAction.Types.MoveElement();
          }
          MoveElement.MergeFrom(other.MoveElement);
          break;
        case InnerOneofCase.RemoveElement:
          if (RemoveElement == null) {
            RemoveElement = new global::AbyssCLI.ABI.RenderAction.Types.RemoveElement();
          }
          RemoveElement.MergeFrom(other.RemoveElement);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::AbyssCLI.ABI.RenderAction.Types.CreateElement subBuilder = new global::AbyssCLI.ABI.RenderAction.Types.CreateElement();
            if (innerCase_ == InnerOneofCase.CreateElement) {
              subBuilder.MergeFrom(CreateElement);
            }
            input.ReadMessage(subBuilder);
            CreateElement = subBuilder;
            break;
          }
          case 18: {
            global::AbyssCLI.ABI.RenderAction.Types.MoveElement subBuilder = new global::AbyssCLI.ABI.RenderAction.Types.MoveElement();
            if (innerCase_ == InnerOneofCase.MoveElement) {
              subBuilder.MergeFrom(MoveElement);
            }
            input.ReadMessage(subBuilder);
            MoveElement = subBuilder;
            break;
          }
          case 26: {
            global::AbyssCLI.ABI.RenderAction.Types.RemoveElement subBuilder = new global::AbyssCLI.ABI.RenderAction.Types.RemoveElement();
            if (innerCase_ == InnerOneofCase.RemoveElement) {
              subBuilder.MergeFrom(RemoveElement);
            }
            input.ReadMessage(subBuilder);
            RemoveElement = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::AbyssCLI.ABI.RenderAction.Types.CreateElement subBuilder = new global::AbyssCLI.ABI.RenderAction.Types.CreateElement();
            if (innerCase_ == InnerOneofCase.CreateElement) {
              subBuilder.MergeFrom(CreateElement);
            }
            input.ReadMessage(subBuilder);
            CreateElement = subBuilder;
            break;
          }
          case 18: {
            global::AbyssCLI.ABI.RenderAction.Types.MoveElement subBuilder = new global::AbyssCLI.ABI.RenderAction.Types.MoveElement();
            if (innerCase_ == InnerOneofCase.MoveElement) {
              subBuilder.MergeFrom(MoveElement);
            }
            input.ReadMessage(subBuilder);
            MoveElement = subBuilder;
            break;
          }
          case 26: {
            global::AbyssCLI.ABI.RenderAction.Types.RemoveElement subBuilder = new global::AbyssCLI.ABI.RenderAction.Types.RemoveElement();
            if (innerCase_ == InnerOneofCase.RemoveElement) {
              subBuilder.MergeFrom(RemoveElement);
            }
            input.ReadMessage(subBuilder);
            RemoveElement = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the RenderAction message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class CreateElement : pb::IMessage<CreateElement>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<CreateElement> _parser = new pb::MessageParser<CreateElement>(() => new CreateElement());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<CreateElement> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::AbyssCLI.ABI.RenderAction.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CreateElement() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CreateElement(CreateElement other) : this() {
          parentId_ = other.parentId_;
          elementId_ = other.elementId_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CreateElement Clone() {
          return new CreateElement(this);
        }

        /// <summary>Field number for the "parent_id" field.</summary>
        public const int ParentIdFieldNumber = 1;
        private int parentId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int ParentId {
          get { return parentId_; }
          set {
            parentId_ = value;
          }
        }

        /// <summary>Field number for the "element_id" field.</summary>
        public const int ElementIdFieldNumber = 2;
        private int elementId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int ElementId {
          get { return elementId_; }
          set {
            elementId_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as CreateElement);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(CreateElement other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (ParentId != other.ParentId) return false;
          if (ElementId != other.ElementId) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (ParentId != 0) hash ^= ParentId.GetHashCode();
          if (ElementId != 0) hash ^= ElementId.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (ParentId != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(ParentId);
          }
          if (ElementId != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(ElementId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (ParentId != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(ParentId);
          }
          if (ElementId != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(ElementId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (ParentId != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(ParentId);
          }
          if (ElementId != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(ElementId);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(CreateElement other) {
          if (other == null) {
            return;
          }
          if (other.ParentId != 0) {
            ParentId = other.ParentId;
          }
          if (other.ElementId != 0) {
            ElementId = other.ElementId;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                ParentId = input.ReadInt32();
                break;
              }
              case 16: {
                ElementId = input.ReadInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                ParentId = input.ReadInt32();
                break;
              }
              case 16: {
                ElementId = input.ReadInt32();
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class MoveElement : pb::IMessage<MoveElement>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<MoveElement> _parser = new pb::MessageParser<MoveElement>(() => new MoveElement());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<MoveElement> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::AbyssCLI.ABI.RenderAction.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public MoveElement() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public MoveElement(MoveElement other) : this() {
          elementId_ = other.elementId_;
          newParentId_ = other.newParentId_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public MoveElement Clone() {
          return new MoveElement(this);
        }

        /// <summary>Field number for the "element_id" field.</summary>
        public const int ElementIdFieldNumber = 1;
        private int elementId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int ElementId {
          get { return elementId_; }
          set {
            elementId_ = value;
          }
        }

        /// <summary>Field number for the "new_parent_id" field.</summary>
        public const int NewParentIdFieldNumber = 2;
        private int newParentId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int NewParentId {
          get { return newParentId_; }
          set {
            newParentId_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as MoveElement);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(MoveElement other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (ElementId != other.ElementId) return false;
          if (NewParentId != other.NewParentId) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (ElementId != 0) hash ^= ElementId.GetHashCode();
          if (NewParentId != 0) hash ^= NewParentId.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (ElementId != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(ElementId);
          }
          if (NewParentId != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(NewParentId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (ElementId != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(ElementId);
          }
          if (NewParentId != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(NewParentId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (ElementId != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(ElementId);
          }
          if (NewParentId != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(NewParentId);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(MoveElement other) {
          if (other == null) {
            return;
          }
          if (other.ElementId != 0) {
            ElementId = other.ElementId;
          }
          if (other.NewParentId != 0) {
            NewParentId = other.NewParentId;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                ElementId = input.ReadInt32();
                break;
              }
              case 16: {
                NewParentId = input.ReadInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                ElementId = input.ReadInt32();
                break;
              }
              case 16: {
                NewParentId = input.ReadInt32();
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class RemoveElement : pb::IMessage<RemoveElement>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<RemoveElement> _parser = new pb::MessageParser<RemoveElement>(() => new RemoveElement());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<RemoveElement> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::AbyssCLI.ABI.RenderAction.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public RemoveElement() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public RemoveElement(RemoveElement other) : this() {
          elementId_ = other.elementId_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public RemoveElement Clone() {
          return new RemoveElement(this);
        }

        /// <summary>Field number for the "element_id" field.</summary>
        public const int ElementIdFieldNumber = 1;
        private int elementId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int ElementId {
          get { return elementId_; }
          set {
            elementId_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as RemoveElement);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(RemoveElement other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (ElementId != other.ElementId) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (ElementId != 0) hash ^= ElementId.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (ElementId != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(ElementId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (ElementId != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(ElementId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (ElementId != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(ElementId);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(RemoveElement other) {
          if (other == null) {
            return;
          }
          if (other.ElementId != 0) {
            ElementId = other.ElementId;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                ElementId = input.ReadInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                ElementId = input.ReadInt32();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
