// Code generated by "stringer -type=FrameType"; DO NOT EDIT.

package pcn

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ID-0]
	_ = x[JN-1]
	_ = x[JOK-2]
	_ = x[JDN-3]
	_ = x[JNI-4]
	_ = x[MEM-5]
	_ = x[SNB-6]
	_ = x[CRR-7]
	_ = x[RST-8]
	_ = x[PINGT-60]
	_ = x[PINGR-61]
}

const (
	_FrameType_name_0 = "IDJNJOKJDNJNIMEMSNBCRRRST"
	_FrameType_name_1 = "PINGTPINGR"
)

var (
	_FrameType_index_0 = [...]uint8{0, 2, 4, 7, 10, 13, 16, 19, 22, 25}
	_FrameType_index_1 = [...]uint8{0, 5, 10}
)

func (i FrameType) String() string {
	switch {
	case i <= 8:
		return _FrameType_name_0[_FrameType_index_0[i]:_FrameType_index_0[i+1]]
	case 60 <= i && i <= 61:
		i -= 60
		return _FrameType_name_1[_FrameType_index_1[i]:_FrameType_index_1[i+1]]
	default:
		return "FrameType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
